### PR TITLE
Find plugin location to correctly link sound file

### PR DESCRIPTION
**Pull request by gegere**
Hope you understand what is going on with this pull-request, I updated the code to find the plugins folder based on the location of the plugin which will be dynamic. I have a server hosting many Open-VBX installations for various customers. These installations are not residing in the root path of the system. Many of them are in subfolders.

An example for a OpenVBX login might be the following.
`https://usa1.openphon.co/petgrooming`

Based your quick fix the mp3 would still not be found, this pull request fixes this issue.

### CODE REVIEW

**Comment by jpwalters** [comment]
I guess I should have tested this before merging because this commit doesn't work on my server.

Here's the output of the current code:

```
<audio id="notify">
  <source src="/var/www/clients/client1/web62/web/plugins/sms-conversation/assets/notify.mp3" />
</audio>
```

**Comment by gegere** [comment]
Can you tell me what type of PHP / Apache version you are using?

It seems that the following code is not working? Can you try to run this within a PHP file?

```
dirname ( __FILE__ )
```

**Comment by jpwalters** [comment]
When I run `dirname ( _FILE_ )` I get the following:
`/var/www/clients/client1/web62/web/plugins/sms-conversation`

I'm running the latest version of Apache with ISPConfig control panel installed (http://www.ispconfig.org).

**Comment by gegere** [comment]
Does this work on your server?

```
$_SERVER['DOCUMENT_ROOT'];
```

If you [run the following](http://pastie.org/10684713) in the SMS plugin directory what it the output?

**Comment by jpwalters** [comment]
When I run:

```
<?php

$dir_name = dirname ( __FILE__ );

$dir_root = $_SERVER['DOCUMENT_ROOT'];

$plugin_dir = str_replace( $_SERVER['DOCUMENT_ROOT'], '', $dir_name );

echo $dir_name . '<br />';
echo $dir_root . '<br />';
echo $plugin_dir;

?>
```

I get the following output:

```
/var/www/clients/client1/web62/web/plugins/sms-conversation
/var/www/domain.com/web
/var/www/clients/client1/web62/web/plugins/sms-conversation
```

**Comment by gegere** [comment]
Can you follow the link and run this within the SMS plugin directory? This script should output a relative path where the plugin runs and for the media file to be accessible. There might be a slight tweak but this is the correct direction.

**Comment by jpwalters** [comment]
I just hacked together this code and it seems to be working for me.

```
<audio id="notify">
<?php 
    // Find plugin location to correctly link sound file
    $file = "assets/notify.mp3";
    $found_plugin_dir = false;
    $plugin_dir = "plugins";

    $plugin = OpenVBX::$currentPlugin;
    $info = $plugin->getInfo();
    $path = $info['plugin_path'] .'/'. $file;
    $plugin_dir = implode('/', array('plugins', $info['dir_name'], $file));

    $is_ssl_proto = false;
    switch(true) {
        case !empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] != 'off':
            $is_ssl_proto = true;
            break;
        case !empty($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https':
            $is_ssl_proto = true;
            break;
    }

    $base_url = "http".($is_ssl_proto ? 's' : '') . "://".$_SERVER['HTTP_HOST']. rtrim(WEB_ROOT, '/') . '/';

?>
<source src="<?= $base_url.$plugin_dir ?>"></source>
</audio>
```

**Comment by jpwalters** [comment]
Humm... this still might not solve your problem if OpenVBX is installed in a sub directory but I think this gets closer to solving it.  At least now the code doesn't matter what the name of the plugin folder is.

**Comment by gegere** [comment]
You won't need the `$base_url` no need to check for HTTPS as having a relative file page should be a solution with less code. 

Can you test the command output with this script? http://pastie.org/10684713

**Comment by jpwalters** [comment]
If I don't add the base_url then I only get `plugins/sms-conversation/assets/notify.mp3` which will then be translated to `http://domain.com/p/plugins/sms-conversation/assets/notify.mp3`.  The little extra /p/ invalidates the path and cause a 404 error.

**Comment by gegere** [comment]
Can you test the command output of this script and paste the contents? This script output the following on my Apache build.

http://pastie.org/10684713

This is the output I have for my installation:

```
/var/zpanel/hostdata/zadmin/public_html/openphon1_openphon_co/koko/plugins/sms-conversation
/var/zpanel/hostdata/zadmin/public_html/openphon1_openphon_co
/koko/plugins/sms-conversation
```

**Comment by jpwalters** [comment]
For me I get the following:

```
/var/www/clients/client1/web62/web/plugins/sms-conversation
/var/www/devcallcenter.tek7it.com/web
/var/www/clients/client1/web62/web/plugins/sms-conversation
```

**Comment by gegere** [comment]
Do you have a symlink directory?

Does `/var/www/devcallcenter.tek7it.com/web` symlink to `/var/www/clients/client1/web62/web`

The root directory of this site defined by the 'DocumentRoot' directive of the host .conf file

**Comment by jpwalters** [comment]
`/var/www/devcallcenter.tek7it.com` sysmlinks to `/var/www/clients/client1/web62`.

**Comment by gegere** [comment]
There needs to be a tweak to the `symlink` permissions with the Apache conf.

**How do I get Apache to follow symlinks?**

Can you please review this thread?
http://superuser.com/questions/244245/how-do-i-get-apache-to-follow-symlinks

**Pull request merged**
